### ISSUE TITLE
"More maps" brings up a new window which cannot be removed

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#324] opened 2023-03-20 22:21 UTC
The only way to exit the more maps mode seems to be to reload the page.

Tested on computer, using Chrome

**Comment by ralfstrandell** [comment] 2023-03-21 19:38
The More maps dialog should have a close button or link in the upper right hand corner!
Is this not the case? On what site?
This works both on planetcaver and planetswimmer sites.

**Comment by ralfstrandell** [comment] 2023-03-21 20:08
I cannot repeat this???
Should I apply some style to the close button? Is it hidden on some site?

**Comment by ralfstrandell** [comment] 2023-03-21 20:10
Oh, it's plain as an Old Order Amish.
Will apply some style. Moment.

**Comment by ralfstrandell** [comment] 2023-03-21 20:31
All close buttons now have identical style, white X on blue background.
If the problem is resolved, please close the issue.
If the problem persists, let me know, and we will work on this further.
I am considering this to be resolved.

**Comment by jariarkko** [comment] 2023-03-21 20:53
I tested this, works, thank you!

**Closed as completed** 2023-03-21 22:58 UTC
Labels: bug
