### ISSUE TITLE
"Link text missing" text now appears on buttons on websites that don't use images

### ISSUE THREAD

**Issue by jariarkko** [jariarkko/psgeo#124] opened 2020-08-26 09:41 UTC
This used to work. The code appears to handle this, but maybe some argument list has gotten wrong arguments somewhere.

**Comment by ralfstrandell** [comment] 2020-08-26 09:51
Oh, a stupid bug. It happened when I disabled button texts by making them GLOBALLY empty, but then there were no icon defined on some domains either. Two solutions:

1. put the text back and commit a fix to the issues #120 #122 
2. define images for all domains

working on this.
Duplicate of #120.

**Comment by jariarkko** [comment] 2020-08-26 09:59
Ah yes it also occurred to me that this is due to #120. Never mind. Fix that and this will also be gone. I'm working on enabling images on other sites. At some point.

**Comment by ralfstrandell** [comment] 2020-08-26 10:05
Maybe you want to pull my latest commit, was doing the same

**Comment by jariarkko** [comment] 2020-08-26 10:53
Good, I will check later and not do anything if its already done. But I need to put files in the right places in my website, and that needs a makefile change on my other system.

**Comment by jariarkko** [comment] 2020-08-26 15:38
I think this is now done, and should work.

**Closed** 2020-08-26 15:38 UTC
Labels: bug
